version: '3'
services:
  presenti:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: npm run prod
    depends_on:
      - postgres
    environment:
      DB_HOST: 'postgres'
      DB_NAME: 'presenti'
      DB_USERNAME: 'presenti'
      DB_PASSWORD: 'badbitch'
    ports:
      - '8138:8138'
    working_dir: /root
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: 'presenti'
      POSTGRES_PASSWORD: 'badbitch'
      POSTGRES_DB: 'presenti'