version: '3'
services:
  presenti:
    build: 
      context: packages/server
      dockerfile: Dockerfile
    command: npm run prod
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_NAME: server
      DB_USERNAME: server
      DB_PASSWORD: badbitch
      REDIS_HOST: redis
    ports:
      - '8138:8138'
    working_dir: /root
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: badbitch
      POSTGRES_DB: server
  redis:
    image: redis
    container_name: cache