version: '3'
services:
  presenti:
    build: 
      context: packages/server
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
      - mailer
      - es01
      - auth
    environment:
      AUTH_HOST: auth
      DB_HOST: postgres
      DB_NAME: server
      DB_USERNAME: server
      DB_PASSWORD: badbitch
      REDIS_HOST: redis
      ELASTIC_NODE: http://es01:9200
      MAILER_URL: http://mailer:8443
    ports:
      - '8138:8138'
    working_dir: /root
    volumes:
      - '/root/node_modules'
      - './packages:/root/node_modules/@presenti'
      - './packages/server/dist:/root/dist'
  auth:
    build:
      context: packages/auth
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
      - mailer
      - es01
    environment:
      DB_HOST: postgres
      DB_NAME: server
      DB_USERNAME: server
      DB_PASSWORD: badbitch
      REDIS_HOST: redis
      ELASTIC_NODE: http://es01:9200
      MAILER_URL: http://mailer:8443
    working_dir: /root
    volumes:
      - '/root/node_modules'
      - './packages/auth/dist:/root/dist'
  mailer:
    build:
      context: packages/mailer
      dockerfile: dockerfile
    environment:
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    volumes:
      - mailer_modules:/root/node_modules
      - './packages:/root/node_modules/@presenti'
      - './packages/mailer/dist:/root/dist'
    working_dir: /root
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: badbitch
      POSTGRES_DB: server
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - SERVICE_PORTS=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - SERVICE_PORTS=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - SERVICE_PORTS=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
volumes:
  pgdata:
  data01:
  data02:
  data03:
  mailer_modules: