version: '3'
services:
  presenti:
    build: 
      context: packages/server
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_NAME: server
      DB_USERNAME: server
      DB_PASSWORD: badbitch
      REDIS_HOST: redis
    ports:
      - '8138:8138'
    working_dir: /root
    volumes:
      - '/root/node_modules'
      - './packages/additions/dist:/root/node_modules/@presenti/additions/dist'
      - './packages/server/dist:/root/dist'
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: badbitch
      POSTGRES_DB: server
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: cache
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data
volumes:
  pgdata:
  esdata: