version: '3'
services:
  presenti:
    build: 
      context: packages/server
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_NAME: server
      DB_USERNAME: server
      DB_PASSWORD: badbitch
      REDIS_HOST: redis
    ports:
      - '8138:8138'
    working_dir: /root
    volumes:
      - '/root/packages/additions/node_modules'
      - '/root/packages/client/node_modules'
      - '/root/packages/frontend/node_modules'
      - '/root/packages/logging/node_modules'
      - '/root/packages/modules/node_modules'
      - '/root/packages/renderer/node_modules'
      - '/root/packages/server/node_modules'
      - '/root/packages/slack/node_modules'
      - '/root/packages/utils/node_modules'
      - '/root/packages/web/node_modules'
      - '/root/node_modules'
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: badbitch
      POSTGRES_DB: server
  redis:
    image: redis
    container_name: cache